[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "routes-planning"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = [
    "bresenham==0.2.1",
    "matplotlib==3.8.0",
    "numpy==1.26.1",
    "utm==0.7.0",
    "rasterio==1.4.1",
    "tifffile==2024.9.20",
    "mplcursors==0.5.3",
    "flet==0.23.2",
    "geopy==2.4.1",
    "redis==5.2.0",
    "boto3==1.35.57",
    "schedule",
    "botocore==1.35.60",
    "pandas==2.2.3",
]
[tool.setuptools.packages.find]
where = ["src"]
