name: 🔖 release

on:
  release:
    types: [created]

jobs:
  update-release:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 📦️ Create ZIP Archive
        run: zip -r ${{ github.event.repository.name }}.zip .

      - name: ⬆️ Upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip

changelog:
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
      notes: |
        - Route to new window after run
        - Download 2 files after validate
        - Color special lines on files
        - Add trigger points
        - Add date input
        - Add pilot interface with table
        - Improve visibility
        - Information on formats